# Generated by Django 2.1.7 on 2022-01-28 14:06

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220128_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to=accounts.models.user_directory_path),
        ),
    ]
