# Generated by Django 2.1.7 on 2022-01-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220128_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='products/%Y/%m/%d/'),
        ),
    ]
