# Generated by Django 4.0.2 on 2022-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220221_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
