# Generated by Django 4.0.2 on 2022-04-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
