# Generated by Django 4.0.2 on 2022-04-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_message', '0003_dualpayam_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dualpayam',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
