# Generated by Django 4.0 on 2022-01-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_prodvote_prodcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodvote',
            old_name='post',
            new_name='product',
        ),
    ]
