name: Docker Compose Deployment

# on:
#   push:
#     branches:
#       - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo docker-compose -f path/to/your/docker-compose.yml build
        sudo docker-compose -f path/to/your/docker-compose.yml up -d

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /path/to/your/project
          sudo docker-compose -f path/to/your/docker-compose.yml down
          sudo docker-compose -f path/to/your/docker-compose.yml pull
          sudo docker-compose -f path/to/your/docker-compose.yml up -d

